name: Bug Report
description: Report a bug you encountered.
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug.
        Please provide as much detail as possible to help us resolve it quickly.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Describe the issue you encountered.
      placeholder: Explain what happened and under what circumstances.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: List the steps to reproduce the bug.
      placeholder: |
        1. Run '...'
        2. Enter '...'
        3. Error occurs
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened? Include any error messages.
    validations:
      required: true

  - type: dropdown
    id: host
    attributes:
      label: MCP Host
      description: Which MCP client were you using?
      options:
        - Claude Code
        - Codex
        - Gemini CLI
        - Copilot CLI
        - Other
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: Node.js Version
      description: "Output of `node --version`"
      placeholder: "v22.0.0"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      placeholder: "macOS 15.2 / Ubuntu 24.04 / Windows 11"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: |
        If available, attach logs from running with `AA_MCP_LOG_LEVEL=debug`.
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Any additional context, screenshots, or configuration files.
