import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { getAgent } from "../agents/registry.js";
import { addEntry, getOrCreateActiveSession } from "../session/store.js";

const SCHEMA = {
	agent: z.enum(["claude", "codex", "gemini", "copilot"]).describe("Agent to generate tests with"),
	code: z.string().describe("Code to generate tests for"),
	framework: z
		.enum(["jest", "vitest", "pytest", "kotest"])
		.optional()
		.describe("Test framework (auto-detected if omitted)"),
	timeout: z.number().optional().describe("Timeout in ms"),
};

export function registerGenerateTestTool(server: McpServer): void {
	server.tool(
		"generate_test",
		"Generate tests for code using a specific agent. Auto-detects or specify test framework.",
		SCHEMA,
		async (params) => {
			const agent = getAgent(params.agent);
			if (!agent) {
				return {
					content: [{ type: "text" as const, text: `Agent '${params.agent}' is not available.` }],
				};
			}

			const frameworkHint = params.framework
				? `Use the ${params.framework} test framework.`
				: "Auto-detect the appropriate test framework based on the code language.";

			const prompt = [
				"Generate comprehensive tests for the following code:",
				"",
				"```",
				params.code,
				"```",
				"",
				frameworkHint,
				"",
				"Include:",
				"1. Happy path tests",
				"2. Edge cases",
				"3. Error handling tests",
				"4. Proper test descriptions",
			].join("\n");

			const response = await agent.execute({
				prompt,
				timeout: params.timeout,
			});

			const sessionId = getOrCreateActiveSession();
			addEntry(sessionId, {
				tool: "generate_test",
				agent: response.agent,
				model: response.model,
				prompt,
				response: response.content,
				durationMs: response.durationMs,
				exitCode: response.exitCode,
				error: response.error,
			});

			return {
				content: [
					{
						type: "text" as const,
						text: `## Tests Generated by ${agent.displayName}\n\n${response.content}`,
					},
				],
			};
		},
	);
}
